# This workflow is the entry point for all CI processes.
# It is from here that all other workflows are launched.
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'renovate/**'
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '!.github/workflows/tests.yml'
      - '**.md'
      - .editorconfig
      - .gitignore
      - '.idea/**'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '!.github/workflows/tests.yml'
      - '**.md'
      - .editorconfig
      - .gitignore
      - '.idea/**'
      - '.vscode/**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
