# This workflow is the entry point for all CI processes.
# It is from here that all other workflows are launched.
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.idea/**'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.idea/**'
      - '.vscode/**'
concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      APP_VERSION: ${{ steps.APP_VERSION.outputs.APP_VERSION }}
      COMMIT_TIMESTAMP: ${{ steps.COMMIT_TIMESTAMP.outputs.COMMIT_TIMESTAMP }}
    steps:
      - uses: actions/checkout@v4
      - id: COMMIT_TIMESTAMP
        run: echo "COMMIT_TIMESTAMP=$(git show -s --format=%ct ${{ github.sha }})" >> $GITHUB_OUTPUT
      - id: APP_VERSION
        run: echo "APP_VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - run: |
          echo "- \`COMMIT_TIMESTAMP\`: ${{ steps.COMMIT_TIMESTAMP.outputs.COMMIT_TIMESTAMP }}" >> $GITHUB_STEP_SUMMARY
          echo "- \`APP_VERSION\`: ${{ steps.APP_VERSION.outputs.APP_VERSION }}" >> $GITHUB_STEP_SUMMARY

  compile-and-test:
    needs:
      - prepare
    uses: ./.github/workflows/compile-and-test.yml
    with:
      renderer-template: ${{ matrix.renderer-template }}
      app-version: ${{ needs.prepare.outputs.APP_VERSION }}
      build-number: ${{ needs.prepare.outputs.COMMIT_TIMESTAMP }}
    strategy:
      fail-fast: false
      matrix:
        renderer-template:
          - vanilla
          - vanilla-ts
          - vue
          - vue-ts
          - react
          - react-ts
          - react-swc
          - react-swc-ts
          - preact
          - preact-ts
          - lit
          - lit-ts
          - svelte
          - svelte-ts
          - solid
          - solid-ts
#          Qwik Has unresolved upstream issue. So I decided to torn it off for now
#          - qwik
#          - qwik-ts
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    needs:
      - prepare
      - compile-and-test
    uses: ./.github/workflows/deploy.yml
    with:
      renderer-template: ${{ matrix.renderer-template }}
      app-version: ${{ needs.prepare.outputs.APP_VERSION }}
      build-number: ${{ needs.prepare.outputs.COMMIT_TIMESTAMP }}
    strategy:
      fail-fast: false
      matrix:
        renderer-template:
          - vanilla
          - vanilla-ts
          - vue
          - vue-ts
          - react
          - react-ts
          - react-swc
          - react-swc-ts
          - preact
          - preact-ts
          - lit
          - lit-ts
          - svelte
          - svelte-ts
          - solid
          - solid-ts
#          Qwik Has unresolved upstream issue. So I decided to torn it off for now
#          - qwik
#          - qwik-ts


  dependabot:
    permissions:
      contents: write
      pull-requests: write
    needs:
      - compile-and-test
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'cawa-93/vite-electron-builder'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
