# This workflow is the entry point for all CI processes.
# It is from here that all other workflows are launched.
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - 'renovate/**'
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '!.github/workflows/tests.yml'
      - '!.github/workflows/release.yml'
      - '**.md'
      - .editorconfig
      - .gitignore
      - '.idea/**'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '!.github/workflows/tests.yml'
      - '!.github/workflows/release.yml'
      - '.vscode/**'
      - '.idea/**'
      - .gitignore
      - .editorconfig
      - '**.md'
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  TEMPLATES: |
    [
      "vanilla",
      "vanilla-ts",
      "vue",
      "vue-ts",
      "react",
      "react-ts",
      "react-swc",
      "react-swc-ts",
      "preact",
      "preact-ts",
      "lit",
      "lit-ts",
      "svelte",
      "svelte-ts",
      "solid",
      "solid-ts"
    ]
  #          Qwik Has unresolved upstream issue. So I decided to torn it off for now
  #          - qwik
  #          - qwik-ts

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      COMMIT_TIMESTAMP: ${{ steps.COMMIT_TIMESTAMP.outputs.COMMIT_TIMESTAMP }}
      APP_CHANNEL: ${{ steps.APP_CHANNEL.outputs.APP_CHANNEL }}
      APP_VERSION: ${{ steps.APP_VERSION.outputs.APP_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - id: COMMIT_TIMESTAMP
        run: echo "COMMIT_TIMESTAMP=$(git show -s --format=%ct ${{ github.sha }})" >> $GITHUB_OUTPUT
      - id: APP_CHANNEL
        run: echo "APP_CHANNEL=$(if [[ "${{ github.ref }}" == 'refs/heads/develop' ]]; then echo 'beta'; else echo 'latest'; fi)" >> $GITHUB_OUTPUT
      - id: APP_VERSION
        run: echo "APP_VERSION=${{ steps.COMMIT_TIMESTAMP.outputs.COMMIT_TIMESTAMP }}$(if [[ "${{ steps.APP_CHANNEL.outputs.APP_CHANNEL }}" != 'latest' ]]; then echo '-${{ steps.APP_CHANNEL.outputs.APP_CHANNEL }}'; else echo ''; fi)" >> $GITHUB_OUTPUT
      - run: |
          echo "- \`COMMIT_TIMESTAMP\`: ${{ steps.COMMIT_TIMESTAMP.outputs.COMMIT_TIMESTAMP }}" >> $GITHUB_STEP_SUMMARY
          echo "- \`APP_CHANNEL\`: ${{ steps.APP_CHANNEL.outputs.APP_CHANNEL }}" >> $GITHUB_STEP_SUMMARY
          echo "- \`APP_VERSION\`: ${{ steps.APP_VERSION.outputs.APP_VERSION }}" >> $GITHUB_STEP_SUMMARY
  tests:
    needs:
      - prepare
    uses: ./.github/workflows/tests.yml
    with:
      renderer-template: ${{ matrix.renderer-template }}
      app-version: ${{ needs.prepare.outputs.COMMIT_TIMESTAMP }}
    strategy:
      fail-fast: false
      matrix:
        renderer-template: ${{ fromJson(env.TEMPLATES) }}
  release:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    permissions:
      contents: write # Allows this job to create releases
    needs:
      - prepare
#      - tests
    uses: ./.github/workflows/release.yml
    with:
      renderer-template: ${{ matrix.renderer-template }}
      app-version: ${{ needs.prepare.outputs.APP_VERSION }}-${{ matrix.renderer-template }}
      app-channel: ${{ needs.prepare.outputs.APP_CHANNEL }}
    strategy:
      fail-fast: false
      matrix:
        renderer-template: ${{ fromJson(env.TEMPLATES) }}
