name: Deploy

on:
  workflow_call:
    inputs:
      renderer-template:
        required: true
        type: string
      app-version:
        required: true
        type: string
      build-number:
        required: true
        type: string

permissions:
  contents: write

defaults:
  run:
    shell: 'bash'

env:
  NODE_NO_WARNINGS: 1
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  npm_config_audit: false
  npm_config_fund: false


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.renderer-template}}
      url: https://github.com/${{github.repository}}/releases/tag/v${{inputs.app-version}}-${{inputs.renderer-template}}.${{inputs.build-number}}
    steps:
      - name: Set pattern variable
        run: echo "pattern=*-${{inputs.renderer-template}}" >> $GITHUB_ENV
      - name: Download compiled app
        uses: actions/download-artifact@v4
        with:
          pattern: "*-${{inputs.renderer-template}}"
          path: dist
          merge-multiple: true
      - run: gh release create v${{inputs.app-version}}-${{inputs.renderer-template}}.${{inputs.build-number}} dist/*${{inputs.renderer-template}}* dist/latest*.yml --repo ${{github.repository}}
        env:
          GH_TOKEN: ${{ github.token }}
