on:
  workflow_call:
    inputs:
      renderer-template:
        required: true
        type: string
      app-version:
        required: true
        type: string
      app-channel:
        required: false
        type: string
        default: latest

defaults:
  run:
    shell: 'bash'

env:
  NODE_NO_WARNINGS: 1
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  npm_config_audit: false
  npm_config_fund: false

jobs:
  release:
    permissions:
      contents: write # Allows this job to create releases
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - run: npm run create-renderer -- -- --template ${{inputs.renderer-template}}
      - run: npm start --workspace @vite-electron-builder/integrate-renderer

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ inputs.renderer-template }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            npm-${{ runner.os }}-${{ inputs.renderer-template }}-

      - run: npm install
      - run: |
          npm run compile -- \
          --publish 'always' \
          -c.extraMetadata.version=${{inputs.app-version}} \
          -c.extraMetadata.name=${{inputs.renderer-template}}
        env:
          # Code Signing params
          # See https://www.electron.build/code-signing
          # CSC_LINK: ''
          # CSC_KEY_PASSWORD: ''
          # Publishing artifacts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EP_PRE_RELEASE: ${{ inputs.app-channel == 'beta' || inputs.app-channel == 'alpha' }}
