name: Tests
on:
  workflow_call:
    inputs:
      renderer-template:
        required: true
        type: string

defaults:
  run:
    shell: 'bash'

env:
  NODE_NO_WARNINGS: 1
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

jobs:
  typeckeck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - run: npm run create-renderer -- -- --template ${{inputs.renderer-template}}
      - run: npm start --workspace @vite-electron-builder/integrate-renderer
      - run: npm install
      - run: npm run typecheck --if-present

  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - run: npm run create-renderer -- -- --template ${{inputs.renderer-template}}
      - run: npm start --workspace @vite-electron-builder/integrate-renderer
      - run: npm install
      - run: npm run compile

      # I ran into problems trying to run an electron window in ubuntu due to a missing graphics server.
      # That's why this special command for Ubuntu is here
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test --if-present
        if: matrix.os == 'ubuntu-latest'

      - run: npm run test --if-present
        if: matrix.os != 'ubuntu-latest'
