on:
  workflow_call:
    inputs:
      renderer-template:
        required: true
        type: string

defaults:
  run:
    shell: 'bash'

env:
  NODE_NO_WARNINGS: 1
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  npm_config_audit: false
  npm_config_fund: false

jobs:
  typeckeck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-template-with-renderer
        name: Init template with "${{inputs.renderer-template}}" renderer
        with:
          renderer-template: ${{inputs.renderer-template}}
      - run: npm run typecheck --if-present

  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-template-with-renderer
        name: Init template with "${{inputs.renderer-template}}" renderer
        with:
          renderer-template: ${{inputs.renderer-template}}

      - run: rm -rf packages/renderer

      - name: Download compiled app
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os }}-${{inputs.renderer-template}}
          path: dist

      - run: npm run test --if-present
