name: Tests
on: [ workflow_call ]

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        renderer-template: [vanilla, vanilla-ts, vue, vue-ts, react, react-ts, react-swc, react-swc-ts, preact, preact-ts, lit, lit-ts, svelte, svelte-ts, solid, solid-ts, qwik, qwik-ts]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - run: npm run create-renderer -- -- --template ${{matrix.renderer-template}}
        name: Create renderer for ${{matrix.renderer-template}}
      - run: npm start --workspace @vite-electron-builder/integrate-renderer
      - run: npm install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npm run build

      # I ran into problems trying to run an electron window in ubuntu due to a missing graphics server.
      # That's why this special command for Ubuntu is here
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test --if-present
        if: matrix.os == 'ubuntu-latest'

      - run: npm run test --if-present
        if: matrix.os != 'ubuntu-latest'
